# Generated by Django 4.2.16 on 2024-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacion',
            name='salon_210',
            field=models.BooleanField(default=False),
        ),
    ]
